#!/bin/sh

#SBATCH --job-name=A_r_n

#SBATCH --output=A.o

#SBATCH --error=A.error

#SBATCH --partition=savio2

#SBATCH --time=72:00:00

#SBATCH --nodes=4

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=24

# QoS:

#SBATCH --qos=savio_normal

#

# Account:

#SBATCH -A fc_neutronics

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
setenv OMP_NUM_THREAD 24

mpirun -np 4 --map-by ppr:1:node:pe=24 ~/bin/sss2/sss2 -omp 24 A
