#!/bin/sh

#SBATCH --job-name=A_hex_06

#SBATCH --output=A.o

#SBATCH --error=A.error

#SBATCH --partition=savio

#SBATCH --time=72:00:00

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=1

#SBATCH --cpus-per-task=20

# QoS:

#SBATCH --qos=nuclear_savio_normal

#

# Account:

#SBATCH -A co_nuclear

#SBATCH --mail-user=keckler@berkeley.edu
#SBATCH --mail-type=all

# run command
setenv OMP_NUM_THREAD 20

~/bin/sss2/sss2 -omp 20 A
